openapi: 3.0.0
info:
  title: Microdatasus API
  version: 1.0.0
servers:
  - url: https://microdatasus-api.onrender.com
paths:
  /fetch_data:
    get:
      summary: Baixar e processar dados do DataSUS
      parameters:
        - in: query
          name: year_start
          schema:
            type: integer
          required: true
        - in: query
          name: year_end
          schema:
            type: integer
          required: true
        - in: query
          name: uf
          schema:
            type: string
          required: true
        - in: query
          name: information_system
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Dados processados
